[tool.poetry]
name = "pytest-proj-3"
version = "0.1.0"
description = ""
authors = ["Sveta Lalayan <lalayan-svetlana@list.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
